### ISSUE TITLE
Error: dest already exists.

### ISSUE THREAD

**Issue by BlackGlory** [BlackGlory/refile#1]
```
(node:27) UnhandledPromiseRejectionWarning: Error: dest already exists.
    at /usr/src/app/node_modules/fs-extra/lib/move/move.js:41:31
    at /usr/src/app/node_modules/universalify/index.js:22:54
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by BlackGlory** [comment]
Close, because the project is no longer using `fs-extra`.
